#spring:
#  datasource:
#    url: jdbc:mysql://192.168.2.110:3307/gmall_pms?useUnicode=true&useSSL=false&characterEncoding=utf8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root

dubbo:
  application:
    name: gmall-pms
  registry:
    address: zookeeper://192.168.2.110:2181
  protocol:
    name: dubbo
    port: 20880
  consumer:
    check: false
